// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	elastic "github.com/olivere/elastic"
	mock "github.com/stretchr/testify/mock"
)

// ElkInterface is an autogenerated mock type for the ElkInterface type
type ElkInterface struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: url, username, password
func (_m *ElkInterface) NewClient(url string, username string, password string) (*elastic.Client, error) {
	ret := _m.Called(url, username, password)

	var r0 *elastic.Client
	if rf, ok := ret.Get(0).(func(string, string, string) *elastic.Client); ok {
		r0 = rf(url, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(url, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
