// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// RabbitInterface is an autogenerated mock type for the RabbitInterface type
type RabbitInterface struct {
	mock.Mock
}

// GetChannel provides a mock function with given fields:
func (_m *RabbitInterface) GetChannel() *amqp.Channel {
	ret := _m.Called()

	var r0 *amqp.Channel
	if rf, ok := ret.Get(0).(func() *amqp.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Channel)
		}
	}

	return r0
}

// GetConnection provides a mock function with given fields: uri
func (_m *RabbitInterface) GetConnection(uri string) *amqp.Connection {
	ret := _m.Called(uri)

	var r0 *amqp.Connection
	if rf, ok := ret.Get(0).(func(string) *amqp.Connection); ok {
		r0 = rf(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Connection)
		}
	}

	return r0
}

// Publish provides a mock function with given fields: exchange, key, mandatory, immediate, msg
func (_m *RabbitInterface) Publish(exchange string, key string, mandatory bool, immediate bool, msg amqp.Publishing) error {
	ret := _m.Called(exchange, key, mandatory, immediate, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool, bool, amqp.Publishing) error); ok {
		r0 = rf(exchange, key, mandatory, immediate, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
