// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model2 "github.com/softplan/tenkai-api/pkg/dbms/model"
	"github.com/stretchr/testify/mock"
)

// UserDAOInterface is an autogenerated mock type for the UserDAOInterface type
type UserDAOInterface struct {
	mock.Mock
}

// AssociateEnvironmentUser provides a mock function with given fields: userID, environmentID
func (_m *UserDAOInterface) AssociateEnvironmentUser(userID int, environmentID int) error {
	ret := _m.Called(userID, environmentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userID, environmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrUpdateUser provides a mock function with given fields: user
func (_m *UserDAOInterface) CreateOrUpdateUser(user model2.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(model2.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: user
func (_m *UserDAOInterface) CreateUser(user model2.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(model2.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: id
func (_m *UserDAOInterface) DeleteUser(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAllUsers provides a mock function with given fields:
func (_m *UserDAOInterface) ListAllUsers() ([]model2.User, error) {
	ret := _m.Called()

	var r0 []model2.User
	if rf, ok := ret.Get(0).(func() []model2.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model2.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
