// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import helmapi "github.com/softplan/tenkai-api/pkg/service/helm"
import mock "github.com/stretchr/testify/mock"

// HelmCommand is an autogenerated mock type for the HelmCommand type
type HelmCommand struct {
	mock.Mock
}

// SetNewClient provides a mock function with given fields: helmConnection, tillerHost
func (_m *HelmCommand) SetNewClient(helmConnection helmapi.HelmConnection, tillerHost string) {
	_m.Called(helmConnection, tillerHost)
}

// run provides a mock function with given fields:
func (_m *HelmCommand) run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
