// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConventionInterface is an autogenerated mock type for the ConventionInterface type
type ConventionInterface struct {
	mock.Mock
}

// GetKubeConfigFileName provides a mock function with given fields: group, name
func (_m *ConventionInterface) GetKubeConfigFileName(group string, name string) string {
	ret := _m.Called(group, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(group, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
