// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	bytes "bytes"

	mock "github.com/stretchr/testify/mock"
)

// HTTPServiceInterface is an autogenerated mock type for the HTTPServiceInterface type
type HTTPServiceInterface struct {
	mock.Mock
}

// Post provides a mock function with given fields: url, payload
func (_m *HTTPServiceInterface) Post(url string, payload *bytes.Buffer) ([]byte, error) {
	ret := _m.Called(url, payload)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, *bytes.Buffer) []byte); ok {
		r0 = rf(url, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *bytes.Buffer) error); ok {
		r1 = rf(url, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
